### ISSUE TITLE
[TODO][IMPROVEMENT] Avoiding exit() / define auth rules globally, not inside the constructor

### ISSUE THREAD

**Issue by panique** [panique/huge#534]
There's this issue https://github.com/panique/php-login/issues/453 that has been fixed the hard way via using `exit();`. But, using exit() is not clean, as this is bad coding style and it also stops unit tests.

Does anybody have a proper solution for this ? How to change the architecture here ?

**Comment by mhcompendium** [comment]
I ran across this while I was working on my current project, I was trying to find some code snippets of how to do BLOB CRUDing using PDO.

At the end of the database class this anonymous script had:
<div class="highlight highlight-php"><pre>
	/**
	 * close the database connection
	 */
	public function __destruct() {
		// close the database connection
		$this->conn = null;
	}
}
</pre>
</div>

This might be an epiphany, or just another fork in the thought process road on this subject...

**Comment by panique** [comment]
http://www.stackoverflow.com/questions/2747791/why-i-have-to-call-exit-after-redirection-through-headerlocation-in-php

**Comment by soulcanada** [comment]
Hi guys,
i've a possible solution for this issue.

Instead of checking the login inside controller __costruct() method i think that is much more clean to check the authentication before calling the controller, directly in the Application::__construct() method; with this solution the login check is only in one place and will be possible to control which resources to protect using a configuration file placed in the config folder.

```php
// The config/auth.php file
return [
    'dashboard' => '*',
    'login' => 'showProfile,editUsername,editUsername_action',
];
```
The keys are the controllers and the value could be a wildcard (* means all actions inside controller) or a string with comma-separated values that corresponds on which actions to protect.

With this implementation you can/can have:
1. Remove all the Auth::checkAuthentication() calls inside controllers constructor
2. A more readable protection system based on a single file 
3. A single entry point in your code where to check if the user is already logged in

What you think about this proposal?

Sorry if my comment contains some errors but english is not my primary language :smile:

**Comment by panique** [comment]
@soulcanada Wow, this is awesome! Thanks a lot, I'll have a deep look on the weekend. Excellent idea!

**Comment by panique** [comment]
Linked: https://github.com/panique/huge/issues/711
