### ISSUE TITLE
[3.1][architecture] Should we avoid Singletons or not ?

### ISSUE THREAD

**Issue by panique** [panique/huge#585]
HUGE 3.0 has introduced several singletons [**edit:** not sure if these constructs are really singletons], as this was by far the most simple way to implement certain things. The older 2.x versions used proper Dependency injection (for injecting db connections for example) for certain things, but it felt very complicated and bloated the code / architure quite much. This is a step backwards in architecture, but a step forward in usability. Weird situation. However, singletons are not nice, but have a look. For example the way the app gets the configs:

https://github.com/panique/huge/blob/master/application/core/Config.php

```php
<?php

class Config
{
    private static $config;

    public static function get($key)
    {
        if (!self::$config) {
            self::$config = require('../application/config/config.' . Environment::get() . '.php');
        }

        return self::$config[$key];
    }

}

```

This makes it easy to get any config by just doing `Config::get('xxx')` everywhere. But, it also makes testing harder (and hardcore developers angry), you probably know the discussion about the Singleton pattern. In this case the Config class has a global state, it only reads the config file the first time Config::get( ... ) is used.

**My question:**
What do you think ? Is it okay to leave it like that or should this project become cleaner, sticking to modern design patterns and provide a real, fully testable architecture ? Keep in mind that this is just a litte hobby project, not a funded-with-millions Symfony thing.

**Interesting possible attempt on how to test this in phpunit**
https://gist.github.com/cjsaylor/4131481

*Side-note:* In v4.x the project will be built on top of another *real* framework.

**Comment by panique** [comment]
Interesting: Slim framework also uses singletons (!) AND tests them:
https://github.com/codeguy/Slim/blob/master/Slim/Environment.php
test: https://github.com/codeguy/Slim/blob/master/tests/EnvironmentTest.php

**Comment by normai** [comment]
(1) One uneducated question please. Is above class Config code really a singleton? I cannot see any object creation involved, there is no new operator and no constructor, just the static $config variable conditionally filled via require. A singleton would return a object, not an array element. Hm .. perhaps in PHP the difference between object and array is blurred?

(2) Use singletons? IMO sure! It is state of the art pattern for certain requirements. The fact, that it is harder to test seems secondary to me. A clean basic design is primary.

**Comment by panique** [comment]
@normai :) To be honest, I'm also very unsure ! I several examples of how a singleton looks the code was similar to the above... Hmm... Maybe we should ask this on stackoverflow / reddit.

I also think that usability and simple code is okay if it fits the need.

**Comment by normai** [comment]
E.g. in above mentioned https://github.com/codeguy/Slim/blob/master/Slim/Environment.php, you can recognize the singleton from the following two sequences:

(1) This static function lets you retrieve the one and only instance. Note the 'new self()' which creates a regular object. The refresh flag is an auxiliary accessory, not a basic requirement.

   public static function getInstance($refresh = false)
   {
      if (is_null(self::$environment) || $refresh) {
         self::$environment = new self();
      }
   return self::$environment;
   }

(2) The private constructor prevents any instantiation from outside. Because the constructor is private, any object can only be created from inside the class. Thus above getInstance() is the only way you can aquire the object.

   private function __construct($settings = null)
   {
      ...
   }

I think, above Environment.php class is a nice example for a simple singleton without any bells
and whistles. This should suffice the standard situations.

**Comment by slaveek** [comment]
Hi
IMO if something (singleton) can bring some problems with coding, testing functionality and If is another way to go, the app should go without singleton. I like data base connection with singleton. We can be sure that is only one. But this also can bring some problems if someone will need another connection in future.

Config and Text looks like a singleton but they probably not. There is not instantiation of a class.

BTW I'm not sure I like this classes. Do we really have to check environment and config file every time when we need config data. I mean if we need:
Config::get('DEFAULT_CONTROLLER');
Config::get('DEFAULT_ACTION');
Config::get('PATH_CONTROLLER')
Config::get('URL') - probably couple times ;)
Config::get('.....')
Config::get('....')
...
etc.
all of this line check for config.
I think that environment should be checked once on the very begin of the app, use ```require_once``` to be sure that config file is loaded once, then let the Config class very easy operate on array only (maybe with some basic checks eg. ```array_key_exists```).

**Comment by panique** [comment]
@slaveek He, I'm quite sure the config / text class does exactly that: only loading the config file ONE time (and putting the config array to $config), at every call after that the class simply returns the array element.

**Comment by normai** [comment]
@slaveek

> I like data base connection with singleton. We can be sure that is only one. But this also can bring some problems if someone will need another connection in future.

The name 'singleton' implies, that it delivers one and the same object for all it's recipients, and normally it does so. But in general, it is just a generator method to control the object creation.

E.g. it could be used, to hold a certain number of objects and deliver the one or the other after certain rules (e.g. like with a thread pool).

Or it can be used to create one object for all requests from that user, but another object for requests for the other user.

Such behaviour is already demonstrated a little bit in above shown sequence from https://github.com/codeguy/Slim/blob/master/Slim/Environment.php :

public static function getInstance($refresh = false)
{
if (is_null(self::$environment) || $refresh) {
self::$environment = new self();
}
return self::$environment;
}

Here the auxiliary refresh flag makes it possible to recreate the object on demand.

Similarly, you could pass e.g. a user-id with the request, and then deliver each user it's own unique object. To achieve this, the object storage inside the class then can no more be a simple variable like self::$environment, but has to be e.g. an associative array like self::$environment[$userid]. Bingo.

**Comment by normai** [comment]
@panique 

> He, I'm quite sure the config / text class does exactly that: only loading the config file ONE time ..., at every call after that the class simply returns the array element.

That means it works fine. But it is not a singleton as OOP defines it, because it does not create and deliver an object.

Perhaps it might lack the flexibility and power for future expansion, as opposed to an authentic singleton, e.g. like I indicated in above reply to @slaveek. Not sure about the implications, probably it is just a cosmetic taint and perhaps a bit harder to read. IMO no reason to roll up the code.

**Comment by slaveek** [comment]
@panique 
> He, I'm quite sure the config / text class does exactly that: only loading the config file ONE time ..., at every call after that the class simply returns the array element.

Of course it does Chris ;) I'm 100% sure it's works as you expect. One thing that I'm thinking about is performance issue.
Config::get('xxx') 20 times = 20 times check $config is true or not.
I never test that so I'm not sure.
Take care.

**Comment by normai** [comment]
> performance issue.
Config::get('xxx') 20 times = 20 times check $config is true or not.

I think it is fine. It is a function call, and inside the function a boolean. There is no way to do it shorter inside the Config class.

But the caller could save function calls, if he stores the first result in a local variable, and then uses that local variable instead of the function calls. Only in extreme situations, the savings will balance out the code complications. And this may be done of course only for settings which do not change during the caller's live span. But are probably most of the settings will not change, since PHP does serve only one HTTP request and then finishes anyway.
