### ISSUE TITLE
[TRAVIS] develop branch has now a .travis.yml, can somebody please have a look ?

### ISSUE THREAD

**Issue by panique** [panique/huge#601]
He,

i've just added a simple .travis.yml to develop branch to make automated builds possible (against PHP 5.5+, 5.6+ and HHVM), but don't have experience with this, so it's failing for sure.

Link: https://travis-ci.org/panique/huge/

Can somebody with experience have a look and provide a working .travis.yml for this ? Would be awesome! Thanks a lot!

**Comment by tankerkiller125** [comment]
Because Travis uses PHPUnit for PHP testing I highly suggest looking at [the docs](https://phpunit.de/manual/4.5/en/index.html) And then from their you would setup the .travis.yml (after making a phpunit.xml file) to something like
```
language: php
php:
    - 5.5
    - 5.6
    - hhvm
# execute any MySQL that you need to do
before_script:
    - phpenv config-add travisphpconfig.ini
    - mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
    - composer self-update
    - composer update
script: phpunit --configuration phpunit.xml --coverage-text
```
From this it will do the following:
* Tell travis that its PHP and what PHP versions to use
* Include our own custom php.ini as travis doesn't have many enabled by default
* Put any DB's into travis
* Update composer.phar
* Update dependencies
* Run Unit Test

**Comment by panique** [comment]
@tankerkiller125 Using travis without having own tests looks probably totally useless, but my initial idea was to do this to run the tests of the dependencies inside HHVM to receive green status ([help pages here](http://hhvm.h4cc.de/help)) on http://hhvm.h4cc.de/ for the dependency packages (gregwar/captcha and phpmailer/phpmailer). But this was i stupid idea I guess :)

**Comment by tankerkiller125** [comment]
It might still be possible been looking at some one elses .travis file and they simply build the project they don't acctully test it. And because of this it builds and gets the green light but some times it doesn't work on HHVM.
