### ISSUE TITLE
Problem with displaying default avatar on localhost

### ISSUE THREAD

**Issue by taurelisk** [panique/huge#604]
Thanks for awesome project. Everything works just fine. However, i am banging my head with displaying default avatar (function).

As default, avatar should be at public/avatar/ folder, and default image name should be "default". It is, everything is OK, but somehow, i get:

notice: Undefined property: View::$user_avatar_file in application\view\_templates\header.php

I noticed that in AvatarModal there is line:

return Config::get('URL') . Config::get('PATH_AVATARS_PUBLIC') . Config::get('AVATAR_DEFAULT_IMAGE');

If i understood correctly, if user has own avatar - than this code is replaced with other one, but in this case, user dont have own avatar, so as default, it should show default avatar.

I tested this in windows and linux (yes, i did rewrites) localhosts. Both dont displayed avatar. In windows, i am using xampp.

Everyting else works just fine, everything is OK. Just, for this one error, i am banging my head.

Sorry for bad english.

**Comment by panique** [comment]
what exactly is the problem ? This runs perfectly in the demo. Have you changed the code ?

**Comment by taurelisk** [comment]
Avatar is not displaying. No, i have not changed the code, Everything is by default. Avatar is just not showing. Rewrites does no effect.

**Comment by panique** [comment]
Sorry, cannot help you with that (have no idea what could be wrong). Please follow the install instructions and everything will be fine, maybe you've skipped something.

**Comment by oisian1** [comment]
@taurelisk just follow the function from starting to displaying the avatar and var_dump it out at each stage and see if you are getting the expected results, this is not an issue with the code as it's working from a fresh install, although i'm using Wamp

**Comment by taurelisk** [comment]
I have no idea whats wrong. I even reinstalled this project, xampp, all database. Var_dump gives me NULL.

**Comment by panique** [comment]
@taurelisk Just follow the exact install tutorial or use the extremely easy auto-intasller. There's absolutly no reason to use xampp on windows, the tutorials also does not say so! Don't make things more complicated than necessary, especially when there's an auto-installer that does that for you in 30seconds!

1. This code is COMMENTED OUT in the view (!). But, the php inside the comments might be parsed, so you'll get this error.
2. I've checked this inside several setups and it always correctly shows the path (inside the commented out HTML, so the PHP is parsed correctly).

See here: https://github.com/panique/huge/blob/master/application/view/_templates/header.php#L42
This is indeed messy code and should be removed, but it's not the problem.

Please don't get me wrong here, but I've answered several thousands of bug reports and help requests for this project, and in 99% is was because the users didn't follow the install tutorial correctly or had changed the configs in weird ways. That you are using xampp (which nobody should use) on windows (!), even if the tutorial clearly says Ubuntu 14.04 LTS might be a hint here.

Sorry, but I cannot help you with that.
