### ISSUE TITLE
[question] bootstrap.sh

### ISSUE THREAD

**Issue by di48l069** [panique/huge#668]
Hi there does that script still run if the project is private? If not is there anything I must add to it?

**Comment by panique** [comment]
Hey, sorry i really don't know what you mean... Can you give more details ?

**Comment by di48l069** [comment]
I have a private repro using your framework as my login, im also using your script bootstrap.sh but since the project is private i cant run the script because my project is private i changed the clone url to my repro url in the script.

**Comment by panique** [comment]
What's going on on your server has absolutly nothing to do with the repo status! Public repo just means eveerybody can see the and download the code, private repo means just you can see and download the code afaik. I've used HUGE so often from public AND private repos, so that's definitly not the problem.

**Comment by di48l069** [comment]
Thanks
