### ISSUE TITLE
additional field

### ISSUE THREAD

**Issue by trasky365** [panique/huge#671]
How to add extra field in the profile? In the database there is a cell "balance", as in "LoginController/showProfile" add to display?

public function showProfile()
    {
        Auth::checkAuthentication();
        $this->View->render('login/showProfile', array(
            ...
            'user_balance' => Session::get('user_balance'),
            ...
        ));
    }

not working...

**Comment by panique** [comment]
This is a bug forum, not for free personal support, sorry. If you want help, then form a proper question, show what you've tried and what exactly the problem is. The stuff you posted has absolutly nothing to do with your question, and I think that you have not looked at the code at all or tried to do this by yourself, maybe you should take some hours to read into the application, then it's totally obvious and extremely simple.

"Not working" is also not a useful problem description.
