### ISSUE TITLE
Plugin/Theme Development: Skeleton build up

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#686]
A good to implement feature for HUGE would be a "plugin skeleton". I mean a plugin framework for HUGE. So anyone can easily build plugin that can easily integrate with HUGE without customizing the main HUGE core. There will be a plugin and theme folder where there will be a skeleton theme and plugin. Everyone will/can build themes/plugins around that frame. what say?

**Comment by oisian** [comment]
Why not just develop with composer and use that?

**Comment by panique** [comment]
@oisian @abmmhasan I also think using Composer is the way to go here. This little framework is too small and too unpopular to make the stress to build a plugin system (but that's just my personal opinion).

Does anybody have an idea how a theme/plugin feature could look like ?

**Comment by abmmhasan** [comment]
#498 already accepted for 4.0

**Comment by bribrink** [comment]
Perhaps a plugin as optional.. I like the idea but I also love the simple
file layout we have..   Nothing isn't being used..

**Comment by panique** [comment]
He guys, I would also prefer the Composer-solution, because it's absolutly independet from the framework used.

For example, loading a tool that reads .csv files can be used like this (just a random example, maybe not even a good one as PHP can read/write .csv natively, but you get the idea :) ):

**"Install" it via Composer:**
```composer require league/csv```

and then **use it everywhere** in the project like this:
```
$reader = Reader::createFromPath('/path/to/my/file.csv');
$reader->setFlags(SplFileObject::READ_AHEAD|SplFileObject::SKIP_EMPTY);
foreach ($reader as $index => $row) {
    //do something meaningful here with $row !!
    //$row is an array where each item represent a CSV data cell
    //$index is the CSV row index
}
```
Works perfectly with every PHP project in the world. Is there a good reason to do it in another way, personally I don't see the advantage of writing an own module system for this little framework.
