### ISSUE TITLE
ajax .load issue from dashboard/index.php

### ISSUE THREAD

**Issue by lawkout2** [panique/huge#697]
I cannot seem to replace a div's contents from a php file using jquery $("#mydiv").load("include.php") within the dashboard view. I have tried different paths with no luck. Has anyone else tried this?

**Comment by videsignz** [comment]
I have had success using the jQuery $.get() function, but that's about it.

**Comment by panique** [comment]
as this project (like every other framework) does not include raw .php files you'll have to call the URL, not a file, so instead of doing
```
$("#mydiv").load("include.php")
```
simply do
```
$("#mydiv").load("/notes/id/1")
```
or whatever the URL of the path is. You can also call the full URL.

**Comment by mcanatalay** [comment]
Well, there is an issue about "getting JSON". Jquery has a strict policy about "SAME SOURCE". Since we cannot reach php files and give URL adressess, getting JSON response from another php file is impossible. Are there any way to fix that. Actually, I want to ajax file upload for avatar, but I cannot because I cannot take any response from server.
