### ISSUE TITLE
[DOCUMENTATION IDEA] One-page documentation / infographic

### ISSUE THREAD

**Issue by panique** [panique/huge#742]
I really love it when complex things are explained in a very well created infographic / flowchart! 

There was this thing with Design Patterns in programming, after reading two big books I still had no idea how these things worked, but then a simple screenshot of a simple-as-possible code example explained things in a beautiful and get-it-in-under-60-seconds-way.

As this projects tries to go the super-minimal way it would totally make sense to explain the entire application in one or two PDFs / images with a clever visual structure, maybe even ready-for-printing.

FYI the according source files (.ai ? .psd ? .sketch ?) could be saved into the wiki section of the project, the final .pdf/image directly into the repo.

**Comment by abmmhasan** [comment]
That is a real great idea!

**Comment by JFJanssen** [comment]
For a first version, one could try to generate the flow chart from the code base; what is embedded in what, what links to what, etc.

The result of that can be generated so that it is 100% correct.
All that may be left then, is to make it pretty for printing.

Another bonus is that the generation gathers meta data which is machine readable; this, in turn, can be generate software tests with, and then you can test everything that you want, and proof that you have covered all your bases with these tests.

**Comment by panique** [comment]
Coming up! (so I'll close this ticket)
