### ISSUE TITLE
[FIX] session get with XSS filter problem

### ISSUE THREAD

**Issue by gujiman** [panique/huge#746]
currently when we use the session GET function, it filters the session value for XSS i.e:

https://github.com/panique/huge/blob/master/application/core/Session.php#L44

Everytime time we call the session GET function on the same value, the value gets filtered and stored again. The problem is when we have a session value that contains and '&', then this value will get over filtered, i.e:

For example the gravater url is set with the following value:
Session::set('user_gravatar_image_url', 'gravatar.com?s=1&d=2&r=3');

Now suppose we get this value via session Get:
Session::get('user_gravatar_image_url');

output: 'gravatar.com?s=1&d=2&r=3';

however if you repeat Session::get('user_gravatar_image_url') a few times then we get:

output: 'gravatar.com?s=1&amp;amp;amp;amp;d=2&amp;amp;amp;amp;r=3';

Thats because the '&' here gets  filtered for XSS and Saved over and over again.

My fix is to change:
https://github.com/panique/huge/blob/master/application/core/Session.php#L44

to:
$value = $_SESSION[$key];
return Filter::XSSFilter($value);

**Comment by geozak** [comment]
Why are we using XSS filtering on the SESSION variables?

The SESSION variables can only be modified server side so there shouldn't be XSS in the SESSION variable to begin with.
Unless the program is assigning values directly from GET or POST variables, however this should be prevented by filter the GET or POST not the SESSION.

I think a better solution would be to modify the Request.php post() and get() methods to offer filtering e.g. get($key, $clean) and post($key, $clean), where if $clean is true the appropriate value is returned with XSS filtering applied. With this solution I would also think that the default value for $clean should be true since more often than not you will want to sanitize all user input.

On the note of the Request.php post method. Why is it using strip_tags to "clean" the input rather than the htmlspecialchars? Wouldn't it be better to convert the tags to safe characters than remove them?
For example if the information being cleaned was like a username, the name "some<br />person" and "some<hr />" person would be changed into the same thing and when the user sees their name on the page it would match what they were expecting.

**Comment by geozak** [comment]
Why are we doing XSS filtering on SESSION variables?

SESSION variables can only be modified server side so the stored information should already be clean. Unless the program/developer assigns a SESSION variable to unsanitized user input i.e. GET and POST.

Wouldn't it be better to give the option to sanitize the Request.php get() and post() methods, i.e. get($key, $clean) and post($key, $clean), where if $clean is true we return the value with XSS filtering. With change that I think it would be good to make $cleans default to be true since user input should be sanitized more often than not.

Also talking about Resquest::post(), why do we use strip_tags to clean it instead of htmlspecialchars? Wouldn't it be better to convert the tags to safe characters instead of removing them? For example say your filtering usernames, the usernames "some<br />person" and "some<hr />person" would strip to the same text, and when the user sees their name on the screen it wouldn't like what they expected.

**Comment by dekleinson** [comment]
Hellow,
Hope y'll doing good out there..

Am a 3rd year student doing Bachelor Degree of Software Engineering here in
Bugema University, Uganda.

Am doing my Open Source Software project and i need your cooperation.

Any kind of support will be highly appreciated.
THANKS IN ADVANCE.

**Comment by slaveek** [comment]
@geozak security, security and security. That's probably the main reason to XSS filtering the SESSION variables.  Maybe in some aspects of the project you can encounter to much of security but this is main point.
I think you are right. Definitely GET or POST should be XSS filtered. If SESSION variables for any reason have to be filtered maybe better implement Filter::XSSFilter() in Session::add() method.

**Once** filtered value is safe stored in SESSION array and app don't need to fire up XSSFilter 
**Once** filtered value can fix @gujiman problem (read first post)

**Comment by panique** [comment]
Fixed in dev+master branch! Thanks to geozak for https://github.com/panique/huge/pull/748
