### ISSUE TITLE
[QUESTION] Composer: Required!!!!!!!!!

### ISSUE THREAD

**Issue by abmmhasan** [panique/huge#759]
Well, I think I've been using your old huge version earlier. I downloaded this again yesterday. And then I found out it is now totally depending on Composer!!!!!!! Why!? 
I understand side-load by Composer & I only like composer for optional things but not required things. Can you do a simple rewrite again alike the previous composer independent script! :(
Please keep this request! I understand your time limit! But Just only half an hour from that time for simple rewrite! Please!

**Comment by panique** [comment]
What exactly is your problem ? I don't understand this question to be honest. Composer is the absolute minimum in every PHP project in the world, and if this is problem for whatever reason, then please have a look at php-login-minimal, this might be what you need (find it on php-login.net).

**Comment by akplgeozak** [comment]
This is definitely not a quick fix because you have to especially recreate composer to download the library's and add them to the autoloadspi.
Just not a simple task.

If the issue is that you can't install composer because of permissions or whatever you can download the composer.phar into the folder with the json file and call "php.exe composer.phar install"

**Comment by panique** [comment]
Yes, I totally agree! "I cannot install composer" is a problem that does not really exist, as Composer is just pure PHP itself, nothing else.

If you are really stuck with this problem, then please have a look at the aawesome composer tutorials everywhere, it's super-easy, runs everywhere and it will make your development so much better, stress-free and faster!

**Comment by geozak** [comment]
Well it is and isn't. The composer installer needs admin needs a certain level of permissions because it installs an executible and modifies the PATH and optionally the context menu. The phar solution is not really easy to find unless you know to look for it. Or in my assumed there was something simple out and relentlessly search for it.

**Comment by panique** [comment]
@abmmhasan Just a quick tip: If you need a real, full linux server (not some webspace hosting) and want to spend absolutly no money, then have a look at Vagrant, it's the de-facto standard these days and it will create a perfect server on your local machine, fully encapsulated. A quick tutorial (in my blog btw :)) http://www.dev-metal.com/setup-professional-local-server-virtual-machine-vagrant-phpstorm/

There's absolutly no good reason to dismiss Composer, really :)
