### ISSUE TITLE
Hide checkAdminAuth with 404 view could improve security?

### ISSUE THREAD

**Issue by ghost** [panique/huge#803]
About checkAdminAuthentication() function in core/Auth.php, actually this:

```
        if (!Session::userIsLoggedIn() || Session::get("user_account_type") != 7) {
            // ... then treat user as "not logged in", destroy session, redirect to login page
            Session::destroy();
            header('location: ' . Config::get('URL') . 'login');
            exit();
        }
```

If user try load a page that not exist like 
domain.com/this/page/not/exist
It return 404 view.

Then if try load an admin page that exist like
domain.com/admin
Lost login (if logged in) and redirect to the homepage. That's said him there's something.

What about change it in:

```
        if (!Session::userIsLoggedIn() || Session::get("user_account_type") != 7) {
            // ... then show user "404 error"
            header('HTTP/1.0 404 Not Found', true, 404);
            // @ needed to avoid strict warning (we can call it in other way here?)
            @View::render('error/404');
            exit();
        }
```

So users can't understand there's a page here, because the result it's the same as real missing page.

**Comment by vizzielli** [comment]
Up + Reset password security:

When you try the forgot password option, you receive the feedback "User not exists" if there's no user/mail in the database related to it.

Clearly, it's ok if we can access with the username, because it is public. But i suggest to avoid to write this if the input format is related to an email address, or you give a private information to those seeking to force another user account.


Would be better to write, in any case, something like:
If this mail address exists, you will receive the mail to reset your password.

**Comment by sr-verde** [comment]
The page exists, why should I send a 404? What you try to do is security by obscurity: https://en.wikipedia.org/wiki/Security_through_obscurity

This is always a bad idea. I think this issue should be closed?

**Comment by panique** [comment]
Thanks, I'll close it! Personally, I think it's a valid concern if you dont want to show attackers (or rival companies) your stuff, but maybe too much for this little framework...
