### ISSUE TITLE
HUGE with MS SQL Server

### ISSUE THREAD

**Issue by sarojthapa60** [panique/huge#852]
I looked at the REQUIREMENTS and it says MySQL. I have my users table in MS SQL Server and am thinking about using HUGE framework. Can I still use HUGE with MS SQL Server?

**Comment by panique** [comment]
Are you sure you want to use a framework on top of EXISTING data ? this is quite insane... It would probably be easier to simply use mysql like the autoinstaller does and import your users.

**Comment by sarojthapa60** [comment]
Hi Panique, I am not trying to use a framework on top of existing data. What I am trying to do is create a login panel with reset and register options and link the user credentials to the table in a ms sql server database. 
I was looking at your php-login-advanced repository. I think that's the one I need. Can I connect to the MS SQL Server database instead of MySql?

**Comment by oisian** [comment]
Hi Sarojthapa, I also use Microsoft SQL due to existing infrastructure, what you will need to do it edit the DatabaseFactory.php file

in the getConnection function you have the options to connect to MySql these need to be changed, 

`$options = array(PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_ERRMODE => PDO::ERRMODE_WARNING);`

` $connectionString = 'sqlsrv:Server=' . Config::get('DB_HOST_SQLSRV') . ';Database=' . Config::get('DB_NAME_SQLSRV');`

`      $this->database = new PDO("$connectionString" , Config::get('DB_USER_SQLSRV'), Config::get('DB_PASS_SQLSRV'), $options);`
`

That is what i use, don't forget however you will need to install the  PHP_PDO_SQLSRV  php extensions on your webserver

**Comment by sarojthapa60** [comment]
Thank you so much oisian. I already have PHP_PDO_SQLSRV installed.
